Cast libusb pollfd callbacks from null pointer to proper type.
This avoids an exception (sometimes a segfault) during Python process
exit with a signature like the following:

Exception ignored in: <bound method USBPoller.__del__ of <usb1.USBPoller object at 0x7f7700e4eda0>>
Traceback (most recent call last):
  File ".../site-packages/usb1/__init__.py", line 1081, in __del__
  File ".../site-packages/usb1/__init__.py", line 2127, in wrapper
  File ".../site-packages/usb1/__init__.py", line 2387, in setPollFDNotifiers
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected CFunctionType instance instead of _ctypes.PyCSimpleType